# ç¶²ç«™åŸºæœ¬è³‡è¨Š
title: " "
description: " "
theme: minima

# ä½¿ç”¨ Minimal Mistakes ä½ˆæ™¯ä¸»é¡Œ
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# ç¤¾äº¤åª’é«”é€£çµ
github_username: "hsin456"
linkedin: "https://www.linkedin.com/in/hsin456"
email: "wendy900513@gmail.com"

# æ’ä»¶ï¼ˆå•Ÿç”¨ SEOã€Sitemap ç­‰ï¼‰
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# SASS èˆ‡ CSS è¨­å®š
sass:
  style: compressed
include:
  - _sass
  - _pages

# è¨­å®šé¦–é æ¨£å¼
defaults:
  - scope:
      path: ""
    values:
      layout: "home"
      author_profile: true
      header:
        overlay_image: "assets/images/header-background.jpg"
        # overlay_filter: "0.5"
        title: "Huang Hsin Pei"
        subtitle: "Master's Student at NYCU"
        align: "center"
      show_excerpts: true

# å°è¦½åˆ—ï¼ˆé¸å–®ï¼‰
header_pages:
  - index.md

navigation:
  - title: "ğŸ“„ Research"
    url: /research/
  - title: "ğŸŒ Map, Food, Smiles"
    url: /map-food-smiles/
    

# å€‹äººè³‡è¨Šï¼ˆå´é‚Šæ¬„ï¼‰
author:
  name: "Huang Hsin Pei"
  avatar: "assets/images/profile.jpg"
  bio: "é»ƒé¦¨éœˆ"
  location: "Taiwan"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/hsin456"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/hsin456"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:wendy900513@gmail.com"


# Markdown è¨­å®š
markdown: kramdown
highlighter: rouge
